// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function ListVolumesJSON() {
  return window['go']['main']['App']['ListVolumesJSON']();
}
