// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListVolumes() {
  return window['go']['app']['App']['ListVolumes']();
}

export function ListVolumesJSON() {
  return window['go']['app']['App']['ListVolumesJSON']();
}

export function OnDomReady(arg1) {
  return window['go']['app']['App']['OnDomReady'](arg1);
}
