// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function ListVolumes():Promise<Array<app.VolumeInfo>>;

export function ListVolumesJSON():Promise<string>;

export function OnDomReady(arg1:context.Context):Promise<void>;
